# Generated by Django 5.1.9 on 2025-05-12 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('prof_id', models.AutoField(primary_key=True, serialize=False)),
                ('prof_fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('prof_lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('prof_room', models.CharField(max_length=50, verbose_name='Room')),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('crs_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Course Code')),
                ('crs_year_lvl', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=50, verbose_name='Year Level')),
                ('crs_sem', models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], max_length=50, verbose_name='Semester')),
                ('crs_name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('crs_unit', models.PositiveSmallIntegerField()),
                ('crs_lec_hours', models.PositiveSmallIntegerField()),
                ('crs_lab_hours', models.PositiveSmallIntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('crs_prerequisite', models.ManyToManyField(blank=True, to='main_app.course')),
                ('prof', models.ForeignKey(db_column='prof_id', on_delete=django.db.models.deletion.CASCADE, to='main_app.professor')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
