# Generated by Django 5.1.9 on 2025-05-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='crs_lab_hours',
            field=models.PositiveSmallIntegerField(verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='course',
            name='crs_lec_hours',
            field=models.PositiveSmallIntegerField(verbose_name='Lec'),
        ),
        migrations.AlterField(
            model_name='course',
            name='crs_unit',
            field=models.PositiveSmallIntegerField(verbose_name='Units'),
        ),
    ]
