# Generated by Django 5.1.9 on 2025-05-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_course_crs_lab_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('sec_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100, verbose_name='Section Name')),
                ('sec_capacity', models.IntegerField(verbose_name='Section Capacity')),
            ],
            options={
                'db_table': 'sections',
            },
        ),
    ]
