# Generated by Django 5.1.9 on 2025-05-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role', models.CharField(default='student', max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_fname', models.CharField(max_length=50)),
                ('stud_lname', models.CharField(max_length=50)),
                ('stud_mname', models.CharField(max_length=50)),
                ('stud_gender', models.CharField(max_length=10)),
                ('stud_contact_num', models.CharField(max_length=15)),
                ('stud_dob', models.DateField()),
                ('stud_address', models.TextField()),
                ('stud_city_add', models.TextField()),
                ('stud_email', models.EmailField(max_length=254)),
                ('stud_program', models.CharField(max_length=100)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
