# Generated by Django 5.1.9 on 2025-05-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_user_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_program',
            field=models.CharField(choices=[('BSIT', 'Bachelor of Science in Information Technology')], default='BSIT', max_length=100),
        ),
    ]
