# Generated by Django 5.1.9 on 2025-05-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_student_stud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
