# Generated by Django 5.1.9 on 2025-05-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_student_stud_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
