# Generated by Django 5.1.9 on 2025-05-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_student_stud_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('acad_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('acad_year_date', models.CharField(max_length=9, unique=True)),
            ],
            options={
                'db_table': 'academic_year',
            },
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'verbose_name': 'Sections'},
        ),
    ]
