# Generated by Django 5.1.9 on 2025-05-13 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_academicyear_alter_sections_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sections',
            options={},
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sched_id', models.AutoField(primary_key=True, serialize=False)),
                ('sched_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10, verbose_name='Day')),
                ('sched_time_start', models.TimeField(verbose_name='Start Time')),
                ('sched_time_end', models.TimeField(verbose_name='End Time')),
                ('crs', models.ForeignKey(db_column='crs_code', on_delete=django.db.models.deletion.CASCADE, to='main_app.course', verbose_name='Course')),
                ('sec', models.ForeignKey(db_column='sec_id', on_delete=django.db.models.deletion.CASCADE, to='main_app.sections', verbose_name='Section')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
