# Generated by Django 5.1.9 on 2025-05-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_sections_options_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='sched_time_end',
            field=models.TimeField(help_text='Format: HH:MM (24-hour clock)', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sched_time_start',
            field=models.TimeField(help_text='Format: HH:MM (24-hour clock)', verbose_name='Start Time'),
        ),
    ]
