# Generated by Django 5.1.9 on 2025-05-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_schedule_sched_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='sched_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, verbose_name='Day'),
        ),
    ]
