# Generated by Django 5.1.9 on 2025-05-14 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_schedule_sched_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('enroll_year_lvl', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=50)),
                ('enroll_sem', models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], max_length=50)),
                ('enroll_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('enroll_date', models.DateField(auto_now_add=True)),
                ('stud_is_regular', models.BooleanField(default=True)),
                ('acad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.academicyear')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollDetail',
            fields=[
                ('enroll_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schedule')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.enrollment')),
            ],
        ),
    ]
