# Generated by Django 5.1.9 on 2025-05-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_enrollment_enrolldetail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enrolldetail',
            table='enroll_detail',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='enrollment',
        ),
    ]
