# Generated by Django 5.1.9 on 2025-05-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_enrolldetail_table_alter_enrollment_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='acad_year',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.DeleteModel(
            name='EnrollDetail',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
