# Generated by Django 5.1.9 on 2025-05-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_enrollment_acad_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_fname', models.CharField(max_length=50)),
                ('admin_lname', models.CharField(max_length=50)),
                ('admin_dob', models.DateField()),
                ('admin_email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
