# Generated by Django 5.1.9 on 2025-05-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_user_user_role_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
