# Generated by Django 5.1.9 on 2025-05-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_student_stud_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='year_level',
            field=models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], default='First Year', max_length=50, verbose_name='For Year Level'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('enroll_year_lvl', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=50, verbose_name='Year Level')),
                ('enroll_sem', models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], max_length=50, verbose_name='Semester')),
                ('enroll_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('enroll_date', models.DateTimeField(auto_now_add=True)),
                ('stud_is_regular', models.BooleanField(default=True)),
                ('acad_year', models.ForeignKey(db_column='acad_year_id', on_delete=django.db.models.deletion.CASCADE, to='main_app.academicyear')),
                ('sec', models.ForeignKey(blank=True, db_column='sec_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.sections')),
                ('stud', models.ForeignKey(db_column='stud_id', on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
            options={
                'db_table': 'enrollment',
            },
        ),
        migrations.CreateModel(
            name='EnrollDetail',
            fields=[
                ('enroll_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('sched', models.ForeignKey(db_column='sched_id', on_delete=django.db.models.deletion.CASCADE, to='main_app.schedule')),
                ('enroll', models.ForeignKey(db_column='enroll_id', on_delete=django.db.models.deletion.CASCADE, to='main_app.enrollment')),
            ],
            options={
                'db_table': 'enroll_detail',
            },
        ),
    ]
