# Generated by Django 5.1.9 on 2025-05-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_sections_year_level_enrollment_enrolldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_mname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
