# Generated by Django 5.1.9 on 2025-05-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_student_stud_mname'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolldetail',
            name='remarks',
            field=models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Incomplete', 'Incomplete'), ('Dropped', 'Dropped')], max_length=20, null=True),
        ),
    ]
