# Generated by Django 5.1.9 on 2025-05-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_enrolldetail_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolldetail',
            name='remarks',
            field=models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=20, null=True),
        ),
    ]
