# Generated by Django 5.1.9 on 2025-05-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_enrolldetail_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolldetail',
            name='remarks',
        ),
    ]
