# Generated by Django 5.1.9 on 2025-05-19 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_remove_enrolldetail_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('acad_id', models.AutoField(primary_key=True, serialize=False)),
                ('acad_remarks', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed')], max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('crs', models.ForeignKey(db_column='crs_code', on_delete=django.db.models.deletion.CASCADE, to='main_app.course', verbose_name='Course')),
                ('enroll', models.ForeignKey(db_column='enroll_id', on_delete=django.db.models.deletion.CASCADE, to='main_app.enrollment', verbose_name='Enrollment')),
                ('stud', models.ForeignKey(db_column='stud_id', on_delete=django.db.models.deletion.CASCADE, to='main_app.student', verbose_name='Student')),
            ],
            options={
                'verbose_name_plural': 'Academic Histories',
                'db_table': 'academic_history',
            },
        ),
    ]
