# Generated by Django 4.2 on 2025-06-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_populate_programs'),
        ('main_app', '0023_academichistory'),
    ]

    operations = [
    ]
